---
# tasks file for composer
- name: COMPOSER | download composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/installer


- name: COMPOSER | install composer
  shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
  args:
    creates: /usr/local/bin/composer


- name: COMPOSER | rename composer.phar to composer
  shell: mv /usr/local/bin/composer.phar /usr/bin/composer
  args:
    creates: /usr/bin/composer


- name: COMPOSER | make composer executable
  file: 
    path: /usr/bin/composer
    mode: a+x
    state: file
