

---

# tasks file for roles/jenkins
- name: JENKINS | Import Jenkins key
  rpm_key:
    key: https://pkg.jenkins.io/redhat/jenkins.io.key
    state: present
    validate_certs: no

- name: JENKINS | Get Jenkins repo
  get_url:
    url: https://pkg.jenkins.io/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: JENKINS| Install Jenkins
  yum: name=jenkins state=latest

- name: JENKINS | Start Jenkins service
  service:
    name: jenkins
    state: started
    enabled: yes

- name: JENKINS | Wait 300 seconds for Jenkins to come up
  wait_for:
    port: 8080
    delay: 5

- name: JENKINS | Stop Jenkins service
  service:
    name: jenkins
    state: stopped
    enabled: yes

- name: JENKINS | Delete Jenkins Home
  file:
    state: absent
    path: /var/lib/jenkins
