---
# tasks file for awslogs
#https://github.com/EffectiveDevOpsWithAWS/code-by-chapter/tree/master/Chapter07/ansible/roles/awslogs

- name: install awslogs 
  yum: 
    name: awslogs 
    state: present 

- name: copy global configuration 
  copy: 
    src: awslogs.conf 
    dest: /etc/awslogs 
  #notify: restart awslogs 

- name: start awslogs and enable it 
  service: 
    name: awslogsd
    state: started 
    enabled: yes 
