---
# tasks file for cassandra-components
- name: CASSANDRA-COMPONENTS | install gmp
  yum: name="{{ item }}" state=present
  with_items:
    -  gmp-devel

- name: CASSANDRA-COMPONENTS | install casssanadra rpms
  yum: name="{{ item }}" state=present
  with_items:
    - http://downloads.datastax.com/cpp-driver/centos/7/dependencies/libuv/v1.13.1/libuv-1.13.1-1.el7.centos.x86_64.rpm
    - http://downloads.datastax.com/cpp-driver/centos/7/dependencies/libuv/v1.13.1/libuv-devel-1.13.1-1.el7.centos.x86_64.rpm
    - http://downloads.datastax.com/cpp-driver/centos/7/cassandra/v2.7.0/cassandra-cpp-driver-2.7.0-1.el7.centos.x86_64.rpm
    - http://downloads.datastax.com/php-driver/centos/7/cassandra/v1.3.2/php71w-cassandra-driver-1.3.2stable-1.el7.centos.x86_64.rpm
