---
# tasks file for roles/awscli


 name: NTP| remove ntp yum packages
  yum: name="{{ item }}" state=removed
  with_items:
   - ntp*

- name: NTP | install chrony yum package
  yum: name="{{ item }}" state=present
  with_items:
   - chrony


- name: CHRONYD | enable service at boot and start service
  service:
   name: chronyd
   state: started
   enabled: yes 
